# ISO 9660 (image_iso9660.c) over discs built by the test.  See test.c.
TEST_NAME := iso9660
TEST_SRCS := test.c
TEST_HARNESS := isolated
EXTRA_SRCS := ../../../../src/core/storage/image_iso9660.c
USE_SOURCE_LAYER := 1
include ../../common.mk
