#!/bin/sh
# nt-pid.sh <product-id.txt> <out.script>
#
# Writes the include ans-nt-install/test.script uses to type the Windows NT
# Product ID on GUI Setup's Registration page.
#
# The ID is the owner's own (it is on the CD's Certificate of Authenticity),
# so it lives beside the other fixtures, never in the repository.  It is
# typed one ADB key at a time rather than with keyboard.type(): that paces
# transitions 4 ms apart, inside one 11 ms Cuda auto-poll, and NT's ADB
# path acts on only the first transition of a packet — the rest of the
# digits would go nowhere.  The script language has no way to walk a
# string, hence a generated file.
#
# The three boxes around the literal "OEM" do not auto-advance, so each
# '-' separator becomes a Tab; the "OEM" itself is printed by Setup and is
# not typed.  No file, or an empty one, gives nt_have_pid = 0 and the row
# stops at the Registration page.
set -eu
src=$1
out=$2

pid=""
if [ -f "$src" ]; then
    pid=$(tr -d ' \t\r\n' < "$src")
fi

{
    echo "# generated by nt-pid.sh -- do not edit"
    if [ -z "$pid" ]; then
        echo "let nt_have_pid = 0"
        echo "def nt_type_pid() {"
        echo "    return 0"
        echo "}"
        exit 0
    fi
    echo "let nt_have_pid = 1"
    echo "def nt_type_pid() {"
    rest=$(echo "$pid" | sed 's/-OEM-/-/I')
    while [ -n "$rest" ]; do
        c=$(printf '%s' "$rest" | cut -c1)
        rest=$(printf '%s' "$rest" | cut -c2-)
        case "$c" in
            0) k=0x1D ;; 1) k=0x12 ;; 2) k=0x13 ;; 3) k=0x14 ;; 4) k=0x15 ;;
            5) k=0x17 ;; 6) k=0x16 ;; 7) k=0x1A ;; 8) k=0x1C ;; 9) k=0x19 ;;
            -) k=0x30 ;;
            *) echo "nt-pid.sh: unexpected character '$c' in $src" >&2; exit 1 ;;
        esac
        echo "    nt_key(\"$k\")"
    done
    echo "    return 1"
    echo "}"
} > "$out"
