# The Lisa COPS real-time clock: power-on default and set round-trip.  See test.c.

TEST_NAME    := cops_clock
TEST_SRCS    := test.c
TEST_HARNESS := none
STUBS        := assert
EXTRA_SRCS   := ../../../../src/machines/lisa/cops.c
include ../../common.mk
