TEST_NAME := hfsplus
TEST_SRCS := test.c
TEST_HARNESS := isolated
EXTRA_SRCS := ../../../../src/core/storage/image_hfs.c \
              ../../../../src/core/storage/macroman.c
include ../../common.mk
