// SPDX-License-Identifier: MIT
// Copyright (c) pappadf

// mac_globals_data.c
// Mac low-memory global variable definitions for debugging.

#include <stddef.h>
#include <stdint.h>

struct {
    const char *name;
    uint32_t address;
    int size;
    const char *description;
} mac_global_vars[] = {

    {"BusErrVct",          0X0008, 4,   "Bus error vector address"                                   },
    {"MonkeyLives",        0X0100, 2,   "System self-test status; >= 0 is OK"                        },
    {"SysCom",             0X0100, 1,   "System communication area (region marker)"                  },
    {"ScrVRes",            0X0102, 2,   "Screen vertical dots per inch"                              },
    {"ScrHRes",            0X0104, 2,   "Screen horizontal dots per inch"                            },
    {"ScreenRow",          0X0106, 2,   "Row bytes of main screen"                                   },
    {"MemTop",             0X0108, 4,   "Top of usable RAM"                                          },
    {"BufPtr",             0X010C, 4,   "Top of application memory"                                  },
    {"StkLowPt",           0X0110, 4,   "Lowest stack pointer value seen"                            },
    {"HeapEnd",            0X0114, 4,   "Pointer to the end of the heap"                             },
    {"TheZone",            0X0118, 4,   "Pointer to the current heap zone"                           },
    {"UTableBase",         0X011C, 4,   "Pointer to the unit I/O table"                              },
    {"MacJmp",             0x0120, 4,   "MacsBug jump table"                                         },
    {"DskRtnAdr",          0x0124, 4,   "Used by disk driver"                                        },
    {"PollRtnAddr",        0x0128, 4,   "‘Other’ driver locals"                                  },
    {"DskVerify",          0X012C, 1,   "Flag for disk read/verify"                                  },
    {"LoadTrap",           0X012D, 1,   "Flag to trap before launch"                                 },
    {"MmInOK",             0X012E, 1,   "Memory Manager initial checks OK"                           },
    {"CPUFlag",            0X012F, 1,   "CPU type identifier"                                        },
    {"ApplLimit",          0X0130, 4,   "Application heap limit address"                             },
    {"SonyVars",           0x0134, 4,   "Variables for .SONY driver"                                 },
    {"PWMValue",           0x0138, 4,   "Current PWM value"                                          },
    {"PollStack",          0x013A, 4,   "SCC poll data start stack location"                         },
    {"PollProc",           0x013E, 4,   "SCC poll data procedure"                                    },
    {"DskErr",             0X0142, 2,   "Last disk routine error code"                               },
    {"SysEvtMask",         0X0144, 2,   "System event mask"                                          },
    {"SysEvtBuf",          0X0146, 4,   "Pointer to system event buffer"                             },
    {"EventQueue",         0X014A, 10,  "Event queue header"                                         },
    {"EvtBufCnt",          0X0154, 2,   "Max events in system event buffer"                          },
    {"RndSeed",            0X0156, 4,   "Random number generator seed"                               },
    {"SysVersion",         0X015A, 2,   "Version number of RAM-based system"                         },
    {"SEvtEnb",            0X015C, 1,   "SystemEvent call enable/disable flag"                       },
    {"DSWndUpdate",        0X015D, 1,   "Flag to prevent drawing behind alert"                       },
    {"FontFlag",           0x015E, 1,   "Font manager loop flag"                                     },
    {"IntFlag",            0X015F, 1,   "Flag to reduce interrupt disable time"                      },
    {"VBLQueue",           0X0160, 10,  "VBL queue header"                                           },
    {"Ticks",              0X016A, 4,   "System ticks since startup"                                 },
    {"MBTicks",            0X016E, 4,   "Tick count at last mouse down event"                        },
    {"MBState",            0X0172, 1,   "Current state of the mouse button"                          },
    {"Tocks",              0x0173, 4,   "Lisa sub-tick count"                                        },
    {"KeyMap",             0X0174, 16,  "Bitmap of the keyboard state"                               },
    {"KeypadMap",          0X017C, 4,   "Bitmap of the numeric keypad state"                         },
    {"KeyLast",            0X0184, 2,   "ASCII code of last valid keypress"                          },
    {"KeyTime",            0X0186, 4,   "Tick count at last keypress"                                },
    {"KeyRepTime",         0X018A, 4,   "Tick count of last key repeat"                              },
    {"KeyThresh",          0X018E, 2,   "Key repeat threshold"                                       },
    {"KeyRepThresh",       0X0190, 2,   "Key repeat rate"                                            },
    {"Lvl1DT",             0X0192, 32,  "Level-1 interrupt dispatch table"                           },
    {"Lvl2DT",             0X01B2, 32,  "Level-2 interrupt dispatch table"                           },
    {"UnitNtryCnt",        0X01D2, 2,   "Number of entries in unit table"                            },
    {"VIA",                0X01D4, 4,   "VIA base address"                                           },
    {"SCCRd",              0X01D8, 4,   "SCC base read address"                                      },
    {"SCCWr",              0X01DC, 4,   "SCC base write address"                                     },
    {"IWM",                0X01E0, 4,   "IWM (floppy controller) base address"                       },
    {"GetParam",           0X01E4, 20,  "System parameter scratch area"                              },
    {"Scratch20",          0X01E4, 20,  "20-byte scratchpad area"                                    },
    {"SPValid",            0X01F8, 1,   "Parameter RAM validity status"                              },
    {"SysParam",           0X01F8, 20,  "Low-memory copy of PRAM"                                    },
    {"SPATalkA",           0X01F9, 1,   "AppleTalk node hint for modem port"                         },
    {"SPATalkB",           0X01FA, 1,   "AppleTalk node hint for printer port"                       },
    {"SPConfig",           0X01FB, 1,   "Serial port A & B config bits"                              },
    {"SPPortA",            0X01FC, 2,   "Modem port (SCC A) configuration"                           },
    {"SPPortB",            0X01FE, 2,   "Printer port (SCC B) configuration"                         },
    {"SPAlarm",            0X0200, 4,   "Alarm clock time setting"                                   },
    {"SPFont",             0X0204, 2,   "Default application font number - 1"                        },
    {"SPKbd",              0X0206, 1,   "Keyboard repeat threshold and rate"                         },
    {"SPPrint",            0X0207, 1,   "Printer connection settings"                                },
    {"SPVolCtl",           0X0208, 1,   "PRAM speaker volume setting"                                },
    {"SPClikCaret",        0X0209, 1,   "PRAM double-click and caret times"                          },
    {"SPMisc1",            0X020A, 1,   "Miscellaneous PRAM byte 1"                                  },
    {"PCDeskPat",          0X020B, 1,   "Desktop pattern (top bit only)"                             },
    {"SPMisc2",            0X020B, 1,   "Miscellaneous PRAM byte 2"                                  },
    {"Time",               0X020C, 4,   "Seconds since midnight, Jan 1, 1904"                        },
    {"BootDrive",          0X0210, 2,   "Drive number of the boot drive"                             },
    {"JShell",             0x0212, 4,   "Journaling shell state"                                     },
    {"SFSaveDisk",         0X0214, 2,   "Last vRefNum used by Standard File"                         },
    {"HiKeyLast",          0X0216, 2,   "Keyboard variables alias"                                   },
    {"KbdVars",            0X0216, 4,   "Keyboard manager internal variables"                        },
    {"KbdLast",            0X0218, 2,   "Keyboard variables alias (offset +2)"                       },
    {"JKybdTask",          0X021A, 4,   "Pointer to keyboard VBL task"                               },
    {"KbdType",            0X021E, 1,   "Keyboard model number"                                      },
    {"AlarmState",         0X021F, 1,   "Alarm clock status flags"                                   },
    {"MemErr",             0X0220, 2,   "Last Memory Manager error code"                             },
    {"JFigTrkSpd",         0x0222, 4,   "Jump entry for FMFontMetrics"                               },
    {"JDiskPrime",         0x0226, 4,   "Disk driver vector"                                         },
    {"JRdAddr",            0x022A, 4,   "Disk driver vector"                                         },
    {"JRdData",            0x022E, 4,   "Disk driver vector"                                         },
    {"JWrData",            0x0232, 4,   "Disk driver vector"                                         },
    {"JSeek",              0x0236, 4,   "Disk driver vector"                                         },
    {"JSetUpPoll",         0x023A, 4,   "Disk driver vector"                                         },
    {"JRecal",             0x023E, 4,   "Disk driver vector"                                         },
    {"JControl",           0x0242, 4,   "Disk driver vector"                                         },
    {"JWakeUp",            0x0246, 4,   "Disk driver vector"                                         },
    {"JReSeek",            0x024A, 4,   "Disk driver vector"                                         },
    {"JMakeSpdTbl",        0x024E, 4,   "Disk driver vector"                                         },
    {"JAdrDisk",           0x0252, 4,   "Disk driver vector"                                         },
    {"JSetSpeed",          0x0256, 4,   "Disk driver vector"                                         },
    {"NiblTbl",            0x025A, 4,   "End of disk routine vectors"                                },
    {"FlEvtMask",          0x025E, 2,   "Mask of allowable events to flush at FlushEvents"           },
    {"SdVolume",           0X0260, 1,   "Current speaker volume (0-7)"                               },
    {"SdEnable",           0x0261, 1,   "Sound enabled? (byte)"                                      },
    {"SoundPtr",           0X0262, 4,   "Pointer to four-tone sound record"                          },
    {"SoundVars",          0X0262, 32,  "Sound driver variables (region)"                            },
    {"SoundBase",          0X0266, 4,   "Pointer to free-form synth buffer"                          },
    {"SoundVBL",           0X026A, 16,  "Sound VBL task control element"                             },
    {"SoundDCE",           0X027A, 4,   "Pointer to sound driver DCE"                                },
    {"SoundActive",        0X027E, 1,   "Flag indicating sound is active"                            },
    {"SoundLevel",         0X027F, 1,   "Current amplitude in sound buffer"                          },
    {"CurPitch",           0X0280, 2,   "Current pitch for square-wave synth"                        },
    {"Switcher",           0x0282, 8,   "Used by switcher"                                           },
    {"SwitcherTPtr",       0X0286, 4,   "Pointer to Switcher's table"                                },
    {"RSDHndl",            0x028A, 4,   "Resource driver handle (-1 until initialized)"              },
    {"ROM85",              0X028E, 2,   "Flag for ROM version >= $75"                                },
    {"PortAUse",           0X0290, 1,   "Usage status for serial port A"                             },
    {"PortBUse",           0X0291, 1,   "Usage status for serial port B"                             },
    {"ScreenVars",         0x0292, 8,   "Screen driver variables (MacsBug)"                          },
    {"JGNEFilter",         0X029A, 4,   "Pointer to GetNextEvent filter proc"                        },
    {"Key1Trans",          0X029E, 4,   "Pointer to keyboard translator proc"                        },
    {"Key2Trans",          0X02A2, 4,   "Pointer to keypad translator proc"                          },
    {"SysZone",            0X02A6, 4,   "Pointer to the system heap zone"                            },
    {"ApplZone",           0X02AA, 4,   "Pointer to the application heap zone"                       },
    {"ROMBase",            0X02AE, 4,   "Base address of the ROM"                                    },
    {"RAMBase",            0X02B2, 4,   "Base address for RAM-based traps"                           },
    {"ExpandMem",          0X02B6, 4,   "Pointer to expanded memory block"                           },
    {"DSAlertTab",         0X02BA, 4,   "Pointer to system error alert table"                        },
    {"ExtStsDT",           0X02BE, 16,  "SCC external/status dispatch table"                         },
    {"SCCASts",            0X02CE, 1,   "Last SCC A external/status interrupt"                       },
    {"SCCBSts",            0X02CF, 1,   "Last SCC B external/status interrupt"                       },
    {"SerialVars",         0X02D0, 16,  "Async serial driver variables"                              },
    {"ABusVars",           0X02D8, 4,   "Pointer to AppleTalk variables"                             },
    {"ABusDCE",            0X02DC, 4,   "Pointer to AppleTalk DCE"                                   },
    {"FinderName",         0x02E0, 16,  "The name of the Finder [String[15]]"                        },
    {"DoubleTime",         0X02F0, 4,   "Double-click interval in ticks"                             },
    {"CaretTime",          0X02F4, 4,   "Caret blink interval in ticks"                              },
    {"ScrDmpEnb",          0X02F8, 1,   "Screen dump enabled flag"                                   },
    {"ScrDmpType",         0X02F9, 1,   "Screen dump type (full/window)"                             },
    {"TagData",            0X02FA, 14,  "Sector tag info for disk drivers"                           },
    {"BufTgFNum",          0X02FC, 4,   "File tags buffer: file number"                              },
    {"BufTgFFlg",          0X0300, 2,   "File tags buffer: flags"                                    },
    {"BufTgFBkNum",        0X0302, 2,   "File tags buffer: logical block num"                        },
    {"BufTgDate",          0X0304, 4,   "File tags buffer: modification date"                        },
    {"DrvQHdr",            0X0308, 10,  "Queue header for installed drives"                          },
    {"PWMBuf2",            0X0312, 4,   "Pointer to PWM sound buffer"                                },
    {"HpChk",              0X0316, 4,   "Pointer to heap check routine"                              },
    {"Lo3Bytes",           0X031A, 4,   "Constant value $00FFFFFF"                                   },
    {"MaskBC",             0X031A, 4,   "Memory Manager byte count mask"                             },
    {"MaskHandle",         0X031A, 4,   "Memory Manager handle mask"                                 },
    {"MaskPtr",            0X031A, 4,   "Memory Manager pointer mask"                                },
    {"MinStack",           0X031E, 4,   "Minimum stack size for application"                         },
    {"DefltStack",         0X0322, 4,   "Default stack size for application"                         },
    {"MMDefFlags",         0X0326, 2,   "Default zone flags"                                         },
    {"GZRootHnd",          0X0328, 4,   "Root handle for GrowZone"                                   },
    {"GZRootPtr",          0X032C, 4,   "Root pointer for GrowZone"                                  },
    {"GZMoveHnd",          0X0330, 4,   "Moving handle for GrowZone"                                 },
    {"DSDrawProc",         0X0334, 4,   "Pointer to alternate syserror draw proc"                    },
    {"EjectNotify",        0X0338, 4,   "Pointer to disk eject notification proc"                    },
    {"IAZNotify",          0X033C, 4,   "Pointer to world swap notification proc"                    },
    {"FileVars",           0x0340, 184, "File system variables"                                      },
    {"NxtDB",              0x0342, 4,   "Word used when searching a directory"                       },
    {"MaxDB",              0x0344, 2,   "File Manager private"                                       },
    {"FlushOnly",          0x0346, 1,   "Flag used by UnMountVol, FlushVol"                          },
    {"RegRsrc",            0x0347, 1,   "Flag used by File Manager"                                  },
    {"FLckUnlck",          0x0348, 1,   "Flag used by SetFilLock, RstFilLock"                        },
    {"FrcSync",            0x0349, 1,   "When set, all File System calls are synched"                },
    {"NewMount",           0x034A, 2,   "Used by MountVol to flag new mounts"                        },
    {"DrMstrBlk",          0x034C, 2,   "Master directory block in a volume (MFS)"                   },
    {"FCBSPtr",            0x034E, 4,   "Length word of the file-control-block buffer"               },
    {"DefVCBPtr",          0x0352, 4,   "Default volume’s volume control block"                    },
    {"VCBQHdr",            0x0356, 4,   "Header of the volume-control-block queue"                   },
    {"FSQHdr",             0x0360, 4,   "Header of the file I/O queue"                               },
    {"FSQHead",            0x0362, 4,   "First queued command in File System queue"                  },
    {"FSQTail",            0x0366, 4,   "Last File System queue element"                             },
    {"RgSvArea",           0x036A, 38,  "Register save area used by system"                          },
    {"HFSFlags",           0x0376, 4,   "Byte of internal HFS flags"                                 },
    {"CurDirStore",        0X0398, 4,   "Saved directory for Standard File"                          },
    {"ErCode",             0x03A2, 2,   "Disk driver async errors"                                   },
    {"Params",             0x03A4, 50,  "Used by the device manager for I/O param blocks"            },
    {"FSTemp8",            0x03D6, 8,   "Used by File System"                                        },
    {"FSTemp4",            0x03DE, 4,   "Used by File System"                                        },
    {"FSQueueHook",        0x03E2, 4,   "Hook to capture all File System calls"                      },
    {"ExtFSHook",          0x03E6, 4,   "Used by external file system"                               },
    {"DskSwtchHook",       0x03EA, 4,   "Hook for disk switch dialog"                                },
    {"ReqstVol",           0x03EE, 4,   "VCB of off-line or external volume"                         },
    {"ToExtFS",            0x03F2, 4,   "Memory of an external File System"                          },
    {"FSVarEnd",           0x03F6, 4,   "End of File System variables"                               },
    {"DSAlertRect",        0X03F8, 8,   "Rectangle for system error alerts"                          },
    {"JHideCursor",        0x0800, 4,   "Vector used by QuickDraw"                                   },
    {"JShowCursor",        0x0804, 4,   "Vector used by QuickDraw"                                   },
    {"JShieldCursor",      0x0808, 4,   "Vector used by QuickDraw"                                   },
    {"JScrnAddr",          0x080C, 4,   "Vector used by QuickDraw"                                   },
    {"JScrnSize",          0x0810, 4,   "Vector used by QuickDraw"                                   },
    {"JInitCrsr",          0x0814, 4,   "Vector used by QuickDraw"                                   },
    {"JSetCrsr",           0x0818, 4,   "Vector to routine that sets normal cursor"                  },
    {"JCrsrObscure",       0x081C, 4,   "Vector used by QuickDraw"                                   },
    {"JUpdateProc",        0x0820, 4,   "Vector used by QuickDraw"                                   },
    {"ScrnBase",           0X0824, 4,   "Base address of main screen buffer"                         },
    {"MTemp",              0X0828, 4,   "Raw mouse location from interrupts"                         },
    {"RawMouse",           0X082C, 4,   "Un-jerked mouse coordinates"                                },
    {"Mouse",              0X0830, 4,   "Processed mouse coordinates"                                },
    {"CrsrPin",            0X0834, 8,   "Cursor pinning rectangle"                                   },
    {"CrsrRect",           0X083C, 8,   "Cursor hit rectangle"                                       },
    {"TheCrsr",            0X0844, 68,  "Current cursor data"                                        },
    {"CrsrAddr",           0X0888, 4,   "Saved data from under the cursor"                           },
    {"NewCrsrJTbl",        0X088C, 12,  "Jump table for new cursor routines"                         },
    {"JAllocCrsr",         0X088C, 4,   "Vector to cursor allocation routine"                        },
    {"CrsrSave",           0X088C, 64,  "Saved screen data under cursor"                             },
    {"JSetCCrsr",          0X0890, 4,   "Vector to set color cursor routine"                         },
    {"JOpcodeProc",        0X0894, 4,   "Vector for new picture opcodes"                             },
    {"CrsrBase",           0X0898, 4,   "Screen base address for cursor"                             },
    {"CrsrDevice",         0X089C, 4,   "GDevice for the current cursor"                             },
    {"SrcDevice",          0X08A0, 4,   "Source GDevice for StretchBits"                             },
    {"MainDevice",         0X08A4, 4,   "The main screen's GDevice"                                  },
    {"DeviceList",         0X08A8, 4,   "Linked list of GDevices"                                    },
    {"CrsrRow",            0X08AC, 2,   "Row bytes for cursor's screen"                              },
    {"QDColors",           0X08B0, 4,   "Handle to default QD colors"                                },
    {"CrsrVis",            0X08CC, 1,   "Cursor visibility flag"                                     },
    {"CrsrBusy",           0X08CD, 1,   "Cursor lockout semaphore"                                   },
    {"CrsrNew",            0X08CE, 1,   "Flag indicating cursor has changed"                         },
    {"CrsrCouple",         0X08CF, 1,   "Flag for cursor coupled to mouse"                           },
    {"CrsrState",          0X08D0, 2,   "Cursor show/hide nesting level"                             },
    {"CrsrObscure",        0X08D2, 1,   "Cursor obscure semaphore"                                   },
    {"CrsrScale",          0X08D3, 1,   "Flag for cursor scaling enabled"                            },
    {"MouseMask",          0X08D6, 4,   "Vertical/Horizontal mouse mask"                             },
    {"MouseOffset",        0X08DA, 4,   "Vertical/Horizontal mouse offset"                           },
    {"JournalFlag",        0X08DE, 2,   "Journaling state/mode"                                      },
    {"JSwapFont",          0x08E0, 4,   "Jump entry for FMSwapFont"                                  },
    {"WidthListHand",      0x08E4, 4,   "Handle to list of handles of recent width tables"           },
    {"JournalRef",         0X08E8, 2,   "Refnum of journaling device driver"                         },
    {"CrsrThresh",         0X08EC, 2,   "Mouse scaling threshold delta"                              },
    {"JCrsrTask",          0X08EE, 4,   "Address of the cursor VBL task"                             },
    {"WWExist",            0X08F2, 1,   "Flag indicating Window Manager is init"                     },
    {"QDExist",            0X08F3, 1,   "Flag indicating QuickDraw is init"                          },
    {"JFetch",             0X08F4, 4,   "Jump vector for driver Fetch routine"                       },
    {"JStash",             0X08F8, 4,   "Jump vector for driver Stash routine"                       },
    {"JIODone",            0X08FC, 4,   "Jump vector for IODone routine"                             },
    {"CurApRefNum",        0X0900, 2,   "Refnum of current app's res file"                           },
    {"LoadVars",           0X0900, 68,  "Segment loader variables (region)"                          },
    {"LaunchFlag",         0X0902, 1,   "Flag indicating launch vs. chain"                           },
    {"FondState",          0x0903, 1,   "Saved FOND purge state"                                     },
    {"CurrentA5",          0X0904, 4,   "Pointer to current A5 world"                                },
    {"CurStackBase",       0X0908, 4,   "Pointer to current stack base"                              },
    {"LoadFiller",         0x090C, 4,   "Reserved"                                                   },
    {"CurApName",          0X0910, 32,  "Name of the current application"                            },
    {"SaveSegHandle",      0X0930, 4,   "Handle to segment 0"                                        },
    {"CurJTOffset",        0X0934, 2,   "Current jump table offset from A5"                          },
    {"CurPageOption",      0X0936, 2,   "Sound/screen config for Chain/Launch"                       },
    {"HiliteMode",         0X0938, 1,   "Color highlighting mode flags"                              },
    {"LoaderPBlock",       0X093A, 10,  "Parameter block for ExitToShell"                            },
    {"PrintVars",          0x0944, 16,  "Print code variables"                                       },
    {"ChooserBits",        0x0946, 1,   "Bit 7=0, don’t run; Bit 6=0, gray out AppleTalk"          },
    {"LastPGlobal",        0x0954, 4,   "Last Printing Manager global"                               },
    {"ScrapInfo",          0X0960, 4,   "Length of the desk scrap"                                   },
    {"ScrapVars",          0X0960, 32,  "Scrap manager variables (region)"                           },
    {"ScrapHandle",        0X0964, 4,   "Handle to the desk scrap"                                   },
    {"ScrapCount",         0X0968, 2,   "Scrap validation count"                                     },
    {"ScrapState",         0X096A, 2,   "State of the desk scrap"                                    },
    {"ScrapName",          0X096C, 4,   "Pointer to the scrap filename"                              },
    {"ScrapTag",           0X0970, 16,  "Name of the scrap file"                                     },
    {"ScrapEnd",           0X0980, 0,   "End of scrap variables marker"                              },
    {"ApFontID",           0x0984, 2,   "Application font ID—reset from PRAM"                      },
    {"GotStrike",          0x0986, 1,   "Do we have the strike? (Font Manager)"                      },
    {"FMDefaultSize",      0x0987, 1,   "Default size of Font Record"                                },
    {"CurFMInput",         0x0988, 4,   "Current QuickDraw FMInput Record"                           },
    {"CurFMSize",          0x098A, 4,   "Current font size [short]"                                  },
    {"CurFMFace",          0x098C, 1,   "Current font face"                                          },
    {"CurFMNeedBits",      0x098D, 1,   "Does Font Manager need bits?"                               },
    {"CurFMDevice",        0x098E, 4,   "Current font device [short]"                                },
    {"CurFMNumer",         0x0990, 4,   "Current numerator of scale factor [point]"                  },
    {"CurFMDenom",         0x0994, 4,   "Current denominator of scale factor [point]"                },
    {"FOutRec",            0x0998, 4,   "Font Manager output record"                                 },
    {"FOutFontHandle",     0x099A, 4,   "Font bits"                                                  },
    {"FOutBold",           0x099E, 1,   "Bolding factor"                                             },
    {"FOutItalic",         0x099F, 1,   "Italic factor"                                              },
    {"FOutULOffset",       0x09A0, 1,   "Underline offset"                                           },
    {"FOutULShadow",       0x09A1, 1,   "Underline \"halo\""                                         },
    {"FOutULThick",        0x09A2, 1,   "Underline thickness"                                        },
    {"FOutShadow",         0x09A3, 1,   "Shadow factor"                                              },
    {"FOutExtra",          0x09A4, 1,   "Extra horizontal width"                                     },
    {"FOutAscent",         0x09A5, 1,   "Height above baseline"                                      },
    {"FOutDescent",        0x09A6, 1,   "Height below baseline"                                      },
    {"FOutWidMax",         0x09A7, 1,   "Maximum width of character"                                 },
    {"FOutLeading",        0x09A8, 1,   "Space between lines"                                        },
    {"FOutUnused",         0x09A9, 1,   "Reserved"                                                   },
    {"FOutNumer",          0x09AA, 4,   "Numerators of scaling factors [point]"                      },
    {"FOutDenom",          0x09AE, 4,   "Denominators of scaling factors [point]"                    },
    {"FMDotsPerInch",      0x09B2, 4,   "Dots per inch of current device [point]"                    },
    {"FMStyleTab",         0x09B6, 18,  "Style heuristic table supplied by device"                   },
    {"ToolScratch",        0X09CE, 8,   "General purpose 8-byte scratch area"                        },
    {"WindowList",         0X09D6, 4,   "Pointer to the window list"                                 },
    {"SaveUpdate",         0x09DA, 2,   "Enable window update accumulation"                          },
    {"PaintWhite",         0X09DC, 2,   "Flag to paint new windows white"                            },
    {"WMgrPort",           0X09DE, 4,   "Pointer to the Window Manager's port"                       },
    {"DeskPort",           0x09E2, 4,   "Pointer to desk grafPort"                                   },
    {"OldStructure",       0x09E6, 4,   "Where _DrawNew stores its old value"                        },
    {"OldContent",         0x09EA, 4,   "Where _SaveOld stores its old value"                        },
    {"GrayRgn",            0X09EE, 4,   "Handle to the desktop region"                               },
    {"SaveVisRgn",         0x09F2, 4,   "Temporarily saved visRgn"                                   },
    {"DragHook",           0X09F6, 4,   "Pointer to general drag hook procedure"                     },
    {"TempRect",           0X09FA, 8,   "Temporary rectangle for Window Manager"                     },
    {"Scratch8",           0X09FA, 8,   "8-byte scratch area"                                        },
    {"OneOne",             0X0A02, 4,   "Constant value $00010001"                                   },
    {"MinusOne",           0X0A06, 4,   "Constant value $FFFFFFFF"                                   },
    {"TopMenuItem",        0x0A0A, 4,   "Used by the Menu Manager to handle scrolling menus"         },
    {"AtMenuBottom",       0x0A0C, 4,   "Used by the Menu Manager for scrolling menus"               },
    {"IconBitmap",         0x0A0E, 4,   "Used by PlotIcon [bitmap]"                                  },
    {"MenuList",           0x0A1C, 4,   "The current menu list"                                      },
    {"MBarEnable",         0x0A20, 4,   "If nonzero, menubar belongs to desk accessory"              },
    {"CurDeKind",          0x0A22, 2,   "Window kind of deactivated window"                          },
    {"MenuFlash",          0x0A24, 2,   "Number of times to flash menu when selected"                },
    {"TheMenu",            0x0A26, 4,   "Menu ID of the currently highlighted menu"                  },
    {"SavedHandle",        0x0A28, 4,   "Saved bits under a menu"                                    },
    {"MrMacHook",          0x0A2C, 4,   "Old name for MBarHook"                                      },
    {"MenuHook",           0x0A30, 4,   "Procedure called during tracking of the menu"               },
    {"DragPattern",        0x0A34, 4,   "Pattern used to drag controls and windows [pattern]"        },
    {"DeskPattern",        0X0A3C, 8,   "Pattern used to draw the desktop"                           },
    {"DragFlag",           0x0A44, 2,   "Implicit parameter to drag control"                         },
    {"CurDragAction",      0x0A46, 4,   "Implicit action procedure for DragControl"                  },
    {"FPState",            0x0A4A, 6,   "Floating point state"                                       },
    {"TopMapHndl",         0X0A50, 4,   "Handle to top resource map"                                 },
    {"SysMapHndl",         0X0A54, 4,   "Handle to system resource map"                              },
    {"SysMap",             0X0A58, 2,   "Refnum of system resource file"                             },
    {"CurMap",             0X0A5A, 2,   "Refnum of current resource file"                            },
    {"ResReadOnly",        0X0A5C, 2,   "Resource file read-only flag"                               },
    {"ResLoad",            0X0A5E, 2,   "Current SetResLoad state"                                   },
    {"ResErr",             0X0A60, 2,   "Last Resource Manager error code"                           },
    {"TaskLock",           0x0A62, 1,   "Re-entering system task"                                    },
    {"FScaleDisable",      0x0A63, 1,   "If true, disables font scaling"                             },
    {"CurActivate",        0X0A64, 4,   "Pointer to window getting activate event"                   },
    {"CurDeactive",        0X0A68, 4,   "Pointer to window getting deactivate event"                 },
    {"DeskHook",           0X0A6C, 4,   "Pointer to desktop paint/click hook"                        },
    {"TEDoText",           0X0A70, 4,   "Pointer to TextEdit's doText hook"                          },
    {"TERecal",            0X0A74, 4,   "Pointer to TextEdit's recalText hook"                       },
    {"ApplScratch",        0X0A78, 12,  "General purpose 12-byte app scratch"                        },
    {"GhostWindow",        0X0A84, 4,   "Pointer to a window hidden from FrontWindow"                },
    {"CloseOrnHook",       0x0A88, 4,   "Pointer to routine called when closing desk accessories"    },
    {"RestProc",           0X0A8C, 4,   "Resume procedure for InitDialogs"                           },
    {"ResumeProc",         0X0A8C, 4,   "Pointer to resume procedure"                                },
    {"SaveProc",           0x0A90, 4,   "Address of Save failsave procedure"                         },
    {"SaveSP",             0x0A94, 4,   "Save SP for restart or save"                                },
    {"ANumber",            0x0A98, 2,   "ID if last Alert displayed"                                 },
    {"ACount",             0x0A9A, 2,   "Last Alert stage"                                           },
    {"DABeeper",           0x0A9C, 4,   "Current error sound procedure"                              },
    {"TEScrapLength",      0X0AB0, 4,   "Length of the TextEdit scrap"                               },
    {"TEScrpLength",       0X0AB0, 4,   "Length of the TextEdit scrap"                               },
    {"TEScrpHandle",       0X0AB4, 4,   "Handle to the TextEdit scrap"                               },
    {"AppPacks",           0x0AB8, 8,   "Handles to Pack 0 through Pack 7 [8 handles]"               },
    {"SysResName",         0X0AD8, 20,  "Name of the System resource file"                           },
    {"SoundGlue",          0x0AE8, 4,   "Used by sound glue on Mac XL"                               },
    {"AppParmHandle",      0x0AEC, 4,   "Handle to Finder information on launch"                     },
    {"DSErrCode",          0X0AF0, 2,   "Last system error ID"                                       },
    {"ResErrProc",         0X0AF2, 4,   "Pointer to resource error procedure"                        },
    {"TEWdBreak",          0X0AF6, 4,   "Pointer to default word break routine"                      },
    {"TEWordBreak",        0X0AF6, 4,   "Pointer to default word break routine"                      },
    {"DlgFont",            0x0AFA, 2,   "Current font for dialogs"                                   },
    {"TrapAgain",          0x0B00, 4,   "Used by disk switch hook to repeat File System call"        },
    {"KeyMVars",           0X0B04, 2,   "State for ROM key-mapping procedure"                        },
    {"ROMMapHndl",         0X0B06, 4,   "Handle to the ROM resource map"                             },
    {"PWMBuf1",            0x0B0A, 4,   "PWM buffer pointer"                                         },
    {"BootMask",           0x0B0E, 2,   "Used during boot"                                           },
    {"WidthPtr",           0x0B10, 4,   "Pointer to global width table (valid only after FMSWapFont)"},
    {"AtalkHk1",           0x0B14, 4,   "AppleTalk hook"                                             },
    {"AtalkHk2",           0x0B18, 4,   "AppleTalk hook"                                             },
    {"SCSIFlag",           0x0B22, 2,   "Configuration flag for SCSI"                                },
    {"TimeSCSIDB",         0X0B24, 2,   "SCSI+DBRA instruction loop count"                           },
    {"WidthTabHandle",     0x0B2A, 4,   "Handle to the global width table"                           },
    {"SCSIDrvrs",          0x0B2E, 2,   "BitMap for loaded SCSI drivers"                             },
    {"TimeVars",           0x0B30, 4,   "Time Manager variables"                                     },
    {"BtDskRfn",           0x0B34, 2,   "Reference number of boot disk driver"                       },
    {"BootTmp8",           0x0B36, 8,   "Temporary memory used during boot"                          },
    {"T1Arbitrate",        0x0B3F, 1,   "$FF if VIA timer T1 is available"                           },
    {"JDiskSel",           0x0B40, 4,   "Disk driver vector"                                         },
    {"JSendCmd",           0x0B44, 4,   "Disk driver vector"                                         },
    {"JDCDReset",          0x0B48, 4,   "Disk driver vector"                                         },
    {"LastSPExtra",        0x0B4C, 4,   "Most recent value of space extra"                           },
    {"MenuDisable",        0x0B54, 4,   "Menu ID and item of selected item even if disabled"         },
    {"MBDFHndl",           0x0B58, 4,   "Handle to the current MBDF"                                 },
    {"BNMQHd",             0x0B60, 4,   "Head of background notification queue"                      },
    {"RMgrHiVars",         0x0B80, 4,   "RMGR variations extend $B80 through $B9F"                   },
    {"RomMapInsert",       0X0B9E, 1,   "Flag to link ROM resource map"                              },
    {"TmpResLoad",         0X0B9F, 1,   "Temporary ResLoad override value"                           },
    {"IntlSpec",           0X0BA0, 4,   "Pointer to extra international data"                        },
    {"RMgrPerm",           0x0BA4, 1,   "Permission byte for OpenResFile"                            },
    {"WordRedraw",         0X0BA5, 1,   "Flag for TextEdit RecalDraw"                                },
    {"SysFontFam",         0x0BA6, 4,   "Font ID for the System font"                                },
    {"SysFontSize",        0x0BA8, 4,   "Font size for the System font"                              },
    {"MBarHeight",         0X0BAA, 2,   "Height of the menu bar in pixels"                           },
    {"TESysJust",          0X0BAC, 2,   "TextEdit system justification (L-to-R/R-to-L)"              },
    {"HiHeapMark",         0X0BAE, 4,   "High water mark for heap growth"                            },
    {"SegHiEnable",        0X0BB2, 1,   "Flag to disable MoveHHi in LoadSeg"                         },
    {"FDevDisable",        0x0BB3, 4,   "$FF to disable device-defined style extra"                  },
    {"CommToolboxGlobals", 0X0BB4, 4,   "Pointer to Communication Toolbox Globals"                   },
    {"LastFond",           0x0BC2, 4,   "Last font definition record (FOND)"                         },
    {"FondID",             0x0BC6, 2,   "ID of last font definition record (FOND)"                   },
    {"App2Packs",          0x0BC8, 8,   "Handles to Pack 8 through 15 [8 handles]"                   },
    {"MAErrProc",          0x0BE8, 4,   "MacApp error procedure"                                     },
    {"MASuperTab",         0x0BEC, 4,   "MacApp superclass table"                                    },
    {"FractEnable",        0x0BF4, 1,   "If true enables fractional font widths"                     },
    {"UsedFWidths",        0x0BF5, 1,   "Flag saying if fractional widths were used"                 },
    {"FScaleHFact",        0x0BF6, 4,   "Horizontal font scale factor"                               },
    {"FScaleVFact",        0x0BFA, 4,   "Vertical font scale factor"                                 },
    {"SCSIBase",           0X0C00, 4,   "SCSI chip read base address"                                },
    {"SCSIDMA",            0X0C04, 4,   "SCSI DMA base address"                                      },
    {"SCSIHsk",            0X0C08, 4,   "SCSI handshake base address"                                },
    {"SCSIGlobals",        0X0C0C, 4,   "Pointer to SCSI manager Globals"                            },
    {"RGBBlack",           0X0C10, 6,   "RGB value for black"                                        },
    {"RGBWhite",           0X0C16, 6,   "RGB value for white"                                        },
    {"RowBits",            0X0C20, 2,   "Screen width in pixels"                                     },
    {"ColLines",           0X0C22, 2,   "Screen height in pixels"                                    },
    {"ScreenBytes",        0X0C24, 4,   "Total bytes for screen buffer"                              },
    {"NMIFlag",            0X0C2C, 1,   "NMI debounce flag"                                          },
    {"VidType",            0X0C2D, 1,   "Video board type identifier"                                },
    {"VidMode",            0X0C2E, 1,   "Video mode (e.g."                                           },
    {"SCSIPoll",           0X0C2F, 1,   "Flag to poll SCSI device 0 once"                            },
    {"SEVarBase",          0X0C30, 0,   "Base for SE-specific variables"                             },
    {"MMUFlags",           0X0CB0, 1,   "MMU flags (reserved)"                                       },
    {"MMUType",            0X0CB1, 1,   "Type of Memory Management Unit"                             },
    {"MMU32bit",           0X0CB2, 1,   "Flag for 32-bit MMU mode"                                   },
    {"MMUFluff",           0X0CB3, 1,   "Unused byte for MMU alignment"                              },
    {"MMUTbl",             0X0CB4, 4,   "Pointer to MMU mapping table"                               },
    {"MMUTblSize",         0X0CB8, 4,   "Size of MMU mapping table"                                  },
    {"SInfoPtr",           0X0CBC, 4,   "Pointer to Slot Manager info"                               },
    {"ASCBase",            0X0CC0, 4,   "Apple Sound Chip base address"                              },
    {"SMGlobals",          0X0CC4, 4,   "Pointer to Sound Manager Globals"                           },
    {"TheGDevice",         0X0CC8, 4,   "Pointer to the current GDevice"                             },
    {"CQDGlobals",         0X0CCC, 4,   "Pointer to Color QuickDraw Globals"                         },
    {"AuxWinHead",         0x0CD0, 4,   "Auxiliary information for color windows"                    },
    {"AuxCtlHead",         0x0CD4, 4,   "Auxiliary information for color controls"                   },
    {"DeskCPat",           0x0CD8, 4,   "PixPatHandle to desk pixpat"                                },
    {"SetOSDefKey",        0x0CDC, 4,   "Password for SetOSDef"                                      },
    {"ADBBase",            0X0CF8, 4,   "Apple Desktop Bus variables pointer"                        },
    {"WarmStart",          0X0CFC, 4,   "Flag indicating a warm start"                               },
    {"TimeDBRA",           0X0D00, 2,   "DBRA instruction loop count for 1ms"                        },
    {"TimeSCCDB",          0X0D02, 2,   "SCC+DBRA instruction loop count"                            },
    {"SlotQDT",            0X0D04, 4,   "Pointer to slot queue table"                                },
    {"SlotPrTbl",          0X0D08, 4,   "Pointer to slot priority table"                             },
    {"SlotVBLQ",           0X0D0C, 4,   "Pointer to slot VBL queue table"                            },
    {"ScrnVBLPtr",         0X0D10, 4,   "Saved pointer to main screen VBL queue"                     },
    {"SlotTICKS",          0X0D14, 4,   "Pointer to slot tick count table"                           },
    {"AGBHandle",          0x0D1C, 4,   "Handle to AppleTalk global block"                           },
    {"TableSeed",          0X0D20, 4,   "Seed for generating color table IDs"                        },
    {"SRsrcTblPtr",        0X0D24, 4,   "Pointer to slot resource table"                             },
    {"JVBLTask",           0X0D28, 4,   "Jump vector for slot VBL task"                              },
    {"WMgrCPort",          0X0D2C, 4,   "Window Manager's color GrafPort"                            },
    {"VertRRate",          0X0D30, 2,   "Vertical refresh rate for startup"                          },
    {"SynListHandle",      0x0D32, 4,   "A handle to a list of synthesized fonts"                    },
    {"LastFore",           0x0D36, 4,   "Last foreground color used"                                 },
    {"LastMode",           0x0D3E, 2,   "Last drawing mode"                                          },
    {"LastDepth",          0x0D40, 4,   "Word used by Font Manager"                                  },
    {"SavedHilite",        0x0D43, 4,   "Used for state across Becks QD patches"                     },
    {"ChunkyDepth",        0X0D60, 1,   "Pixel depth for chunky video modes"                         },
    {"CrsrPtr",            0X0D62, 4,   "Pointer to cursor save area"                                },
    {"PortList",           0X0D66, 4,   "Linked list of all GrafPorts"                               },
    {"MickeyBytes",        0X0D6A, 4,   "Pointer to internal cursor data"                            },
    {"QDErr",              0X0D6E, 2,   "QuickDraw error code"                                       },
    {"VIA2DT",             0X0D70, 32,  "VIA2 dispatch table for NuBus Macs"                         },
    {"SInitFlags",         0X0D90, 2,   "Flags for the StartInit code"                               },
    {"DTQueue",            0X0D92, 10,  "Deferred task queue header"                                 },
    {"DTQFlags",           0X0D92, 2,   "Flags word of deferred task queue"                          },
    {"DTskQHdr",           0X0D94, 4,   "Pointer to head of deferred task queue"                     },
    {"DTskQTail",          0X0D98, 4,   "Pointer to tail of deferred task queue"                     },
    {"JDTInstall",         0X0D9C, 4,   "Jump vector for deferred task install"                      },
    {"HiliteRGB",          0X0DA0, 6,   "RGB value for selection highlighting"                       },
    {"TimeSCSIDB",         0x0DA6, 4,   "Number of iterations of SCSI access and DBRA"               },
    {"DSCtrAdj",           0X0DA8, 4,   "Centering adjustment for DS alert box"                      },
    {"IconTLAddr",         0X0DAC, 4,   "Address for startup icon placement"                         },
    {"VideoInfoOK",        0X0DB0, 4,   "Flag indicating video card is OK"                           },
    {"EndSRTPtr",          0X0DB4, 4,   "Pointer to end of Slot Resource Table"                      },
    {"SDMJmpTblPtr",       0X0DB8, 4,   "Pointer to SDM jump table"                                  },
    {"JSwapMMU",           0X0DBC, 4,   "Jump vector for SwapMMU routine"                            },
    {"SDMBusErr",          0X0DC0, 4,   "Pointer to Slot Decl Manager bus error handler"             },
    {"LastTxGDevice",      0X0DC4, 4,   "Cached GDevice for text measuring"                          },
};

const size_t mac_global_vars_count = sizeof(mac_global_vars) / sizeof(mac_global_vars[0]);
