TEST_NAME := vfs
TEST_SRCS := test.c image_vfs_stubs.c
TEST_HARNESS := isolated
EXTRA_SRCS := ../../../../src/core/storage/image_apm.c \
              ../../../../src/core/vfs/vfs.c \
              ../../../../src/core/vfs/host_vfs.c
USE_SOURCE_LAYER := 1
include ../../common.mk
