# The SCSI drive catalog's size parser and model lookups
# (src/core/storage/drive_catalog.c).  See test.c.

TEST_NAME    := drive_catalog
TEST_SRCS    := test.c
TEST_HARNESS := none
STUBS        := assert
EXTRA_SRCS   := ../../../../src/core/storage/drive_catalog.c
include ../../common.mk
