TEST_NAME := irq_controller
TEST_SRCS := test.c
TEST_HARNESS := isolated
EXTRA_SRCS := ../../../../src/core/object/value.c \
              ../../../../src/core/object/object.c \
              ../../../../src/core/object/meta.c \
              ../../../../src/core/peripherals/irq_controller.c
include ../../common.mk
