// The UI element inventory (76 element types), each mapped to the primitive
// or surface that draws it and the gallery stories that show it.  The
// gallery's Coverage view lists them and flags an element no story shows;
// `app-states` marks one only the real-workbench screenshots
// (tests/e2e/web2-specs/app-states.spec.ts) cover, `none` one nothing can
// screenshot (a native tooltip).

export interface CoverageItem {
  n: number;
  element: string;
  primitive: string;
  stories: readonly string[];
}

export const COVERAGE: readonly CoverageItem[] = [
  {
    n: 1,
    element: 'Primary button',
    primitive: 'Button primary',
    stories: ['UiButtons', 'ForcedStates'],
  },
  {
    n: 2,
    element: 'Secondary button',
    primitive: 'Button secondary',
    stories: ['UiButtons', 'ForcedStates'],
  },
  { n: 3, element: 'Danger button', primitive: 'Button danger', stories: ['UiButtons', 'Dialogs'] },
  {
    n: 4,
    element: 'Small outlined button',
    primitive: 'Button size=sm',
    stories: ['UiButtons', 'PanelHeader'],
  },
  {
    n: 5,
    element: 'Toolbar icon button',
    primitive: 'IconButton tone=toolbar',
    stories: ['UiButtons', 'DisplayToolbar', 'ForcedStates'],
  },
  {
    n: 6,
    element: 'Small header icon button',
    primitive: 'IconButton size=sm rest=faded',
    stories: ['UiButtons', 'DebugSections'],
  },
  {
    n: 7,
    element: 'Segmented control',
    primitive: 'SegmentedControl',
    stories: ['UiButtons', 'DisplayToolbar'],
  },
  { n: 8, element: 'Toggle chip', primitive: 'ToggleChip', stories: ['UiButtons', 'StatusBar'] },
  {
    n: 9,
    element: 'Link-style row button',
    primitive: 'ActionRow',
    stories: ['WelcomeHome', 'ForcedStates'],
  },
  { n: 10, element: 'Text link', primitive: 'Link', stories: ['UiButtons', 'WelcomeConfig'] },
  {
    n: 11,
    element: 'Close (×) button',
    primitive: 'IconButton icon=close',
    stories: ['Toast', 'Logs'],
  },
  { n: 12, element: 'Status-bar button / item', primitive: 'status bar', stories: ['StatusBar'] },
  { n: 13, element: 'Text input', primitive: 'TextInput', stories: ['UiInputs', 'Dialogs'] },
  {
    n: 14,
    element: 'Inline editable value',
    primitive: 'InlineValueInput',
    stories: ['UiInputs', 'DebugSections'],
  },
  { n: 15, element: 'Select', primitive: 'Select', stories: ['UiInputs', 'WelcomeConfig'] },
  { n: 16, element: 'Checkbox', primitive: 'Checkbox', stories: ['UiInputs', 'PanelHeader'] },
  { n: 17, element: 'Radio', primitive: 'RadioGroup', stories: ['UiInputs', 'Dialogs'] },
  { n: 18, element: 'Number input', primitive: 'NumberInput', stories: ['UiInputs', 'Logs'] },
  {
    n: 19,
    element: 'Form layout',
    primitive: 'Field, FormGrid',
    stories: ['UiForm', 'WelcomeConfig'],
  },
  { n: 20, element: 'Main panel tabs', primitive: 'Tabs variant=panel', stories: ['PanelHeader'] },
  { n: 21, element: 'Sub-tabs + accessory', primitive: 'Tabs variant=sub', stories: ['TabStrip'] },
  {
    n: 22,
    element: 'Main toolbar bar',
    primitive: 'Toolbar, Separator',
    stories: ['DisplayToolbar'],
  },
  { n: 23, element: 'Panel header bar', primitive: 'PanelHeader', stories: ['PanelHeader'] },
  {
    n: 24,
    element: 'Collapsible section',
    primitive: 'CollapsibleSection',
    stories: ['Sections', 'DebugSections'],
  },
  { n: 25, element: 'Resize handle', primitive: 'Sash', stories: ['Splits'] },
  {
    n: 26,
    element: 'Slide transition',
    primitive: 'WelcomeView + motion tokens',
    stories: ['app-states'],
  },
  { n: 27, element: 'Tree row', primitive: 'TreeItem', stories: ['TreeRows', 'TreeKinds'] },
  { n: 28, element: 'Table', primitive: 'Table', stories: ['Table'] },
  { n: 29, element: 'Simple list row', primitive: 'ListRow', stories: ['Images', 'ForcedStates'] },
  { n: 30, element: 'Data row (mono)', primitive: 'ListRow mono', stories: ['DebugSections'] },
  {
    n: 31,
    element: 'Group heading',
    primitive: 'SectionHeading',
    stories: ['DebugSections', 'UiFeedback'],
  },
  {
    n: 32,
    element: 'Empty / hint / loading text',
    primitive: 'Hint',
    stories: ['Logs', 'UiFeedback', 'Table'],
  },
  {
    n: 33,
    element: 'Disassembly view',
    primitive: 'code tokens + Badge',
    stories: ['Disassembly'],
  },
  {
    n: 34,
    element: 'Register grid',
    primitive: 'code tokens + InlineValueInput',
    stories: ['DebugSections'],
  },
  { n: 35, element: 'FPU grid', primitive: 'code tokens', stories: ['DebugSections'] },
  { n: 36, element: 'Hex dump', primitive: 'code tokens', stories: ['DebugSections'] },
  { n: 37, element: 'MMU readout', primitive: 'code tokens + Field', stories: ['DebugSections'] },
  { n: 38, element: 'Mini disassembly', primitive: 'code tokens', stories: ['DebugSections'] },
  { n: 39, element: 'Log line', primitive: 'log tokens', stories: ['Logs'] },
  { n: 40, element: 'Console', primitive: 'console tokens', stories: ['Console'] },
  {
    n: 41,
    element: 'Pill / tag',
    primitive: 'Badge pill',
    stories: ['UiFeedback', 'Disassembly', 'Images'],
  },
  { n: 42, element: 'Count badge', primitive: 'Badge count', stories: ['UiFeedback', 'Sections'] },
  { n: 43, element: 'Progress bar', primitive: 'ProgressBar', stories: ['UiFeedback', 'UrlBoot'] },
  {
    n: 44,
    element: 'Spinner',
    primitive: 'Spinner',
    stories: ['UiFeedback', 'UiButtons', 'TreeRows'],
  },
  {
    n: 45,
    element: 'Pulsing activity dot',
    primitive: 'ActivityDot',
    stories: ['UiFeedback', 'StatusBar'],
  },
  { n: 46, element: 'Status dot', primitive: 'StatusDot', stories: ['UiFeedback', 'StatusBar'] },
  {
    n: 47,
    element: 'Drive activity light',
    primitive: 'DriveLight',
    stories: ['UiFeedback', 'StatusBar'],
  },
  {
    n: 48,
    element: '"Changed" highlight',
    primitive: '--gs-code-changed-*',
    stories: ['DebugSections', 'UiInputs'],
  },
  { n: 49, element: 'Done mark', primitive: 'Icon check', stories: ['UrlBoot'] },
  {
    n: 50,
    element: 'Inline error text',
    primitive: 'Field / Hint tone=error',
    stories: ['Dialogs', 'UrlBoot', 'UiFeedback'],
  },
  { n: 51, element: 'Info callout', primitive: 'Callout', stories: ['UiFeedback'] },
  { n: 52, element: 'Modal dialog', primitive: 'Modal', stories: ['Dialogs', 'NoticeDialogs'] },
  { n: 53, element: 'Popover', primitive: 'Modal variant=popover', stories: ['Logs'] },
  { n: 54, element: 'Context / drop-down menu', primitive: 'Menu', stories: ['ContextMenu'] },
  { n: 55, element: 'Toast', primitive: 'Toast', stories: ['Toast'] },
  {
    n: 56,
    element: 'Drop overlay',
    primitive: 'DropOverlay + drop tokens',
    stories: ['DropOverlay'],
  },
  {
    n: 57,
    element: 'Drop-target highlight',
    primitive: 'data-state=drop-target',
    stories: ['TreeRows'],
  },
  { n: 58, element: 'Tooltip (native)', primitive: 'unchanged', stories: ['none'] },
  {
    n: 59,
    element: 'Native prompt / confirm',
    primitive: 'PromptDialog / ConfirmDialog',
    stories: ['Dialogs'],
  },
  { n: 60, element: 'Status bar', primitive: 'status bar', stories: ['StatusBar'] },
  {
    n: 61,
    element: 'Hero + card',
    primitive: 'Hero, Card',
    stories: ['WelcomeHome', 'UrlBoot', 'UiFeedback'],
  },
  {
    n: 62,
    element: 'Emulated-screen frame',
    primitive: 'screen-frame tokens',
    stories: ['app-states'],
  },
  {
    n: 63,
    element: 'PDF viewer frame',
    primitive: 'Modal variant=wide',
    stories: ['NoticeDialogs'],
  },
  { n: 64, element: 'Startup / crash error page', primitive: 'error page', stories: ['ErrorPage'] },
  { n: 65, element: 'Scrollbars', primitive: 'base.css', stories: ['Logs', 'Console'] },
  {
    n: 66,
    element: 'Text selection + focus ring',
    primitive: 'base.css',
    stories: ['UiInputs', 'UiButtons'],
  },
  { n: 67, element: 'Icons', primitive: 'Icon + sprite', stories: ['Icons'] },
  {
    n: 68,
    element: 'Expandable tree item',
    primitive: 'TreeItem + Disclosure',
    stories: ['TreeRows', 'TreeKinds'],
  },
  {
    n: 69,
    element: 'Toggle switch',
    primitive: 'Switch',
    stories: ['UiFeedback', 'TreeKinds', 'ValueEditors'],
  },
  {
    n: 70,
    element: 'Inline value editor',
    primitive: 'ValueEditor',
    stories: ['ValueEditors', 'TreeKinds'],
  },
  { n: 71, element: 'Path field with listing', primitive: 'PathField', stories: ['ValueEditors'] },
  {
    n: 72,
    element: 'Completion popup',
    primitive: 'menu tokens (CodeMirror)',
    stories: ['app-states'],
  },
  { n: 73, element: 'Find bar', primitive: 'TextInput + IconButton pressed', stories: ['Console'] },
  {
    n: 74,
    element: 'Signature hint and usage block',
    primitive: 'SectionHeading, Callout',
    stories: ['app-states'],
  },
  { n: 75, element: 'Value tree', primitive: 'Disclosure (summary::before)', stories: ['Console'] },
  { n: 76, element: 'Method-argument form', primitive: 'Field, FormGrid', stories: ['UiForm'] },
];
