# The drive-activity lights: I/O counter sums in, light edges out
# (src/core/storage/drive_activity.c).  See test.c.

TEST_NAME    := drive_activity
TEST_SRCS    := test.c
TEST_HARNESS := none
STUBS        := assert
EXTRA_SRCS   := ../../../../src/core/storage/drive_activity.c
include ../../common.mk
