TEST_NAME := object_resolve
TEST_SRCS := test.c
TEST_HARNESS := isolated
EXTRA_SRCS := ../../../../src/core/object/value.c \
              ../../../../src/core/object/object.c
include ../../common.mk
