TEST_NAME := object_method
TEST_SRCS := test.c
TEST_HARNESS := isolated
EXTRA_SRCS := ../../../../src/core/object/value.c \
              ../../../../src/core/object/object.c \
              ../../../../src/core/object/parse.c \
              ../../../../src/core/object/expr.c
include ../../common.mk
