# Shared storage helpers (src/core/storage/storage_util.c): mkdir -p, rm -r,
# the capped file reader, the JSON escaper, the atomic writer.

TEST_NAME := storage_util
TEST_SRCS := test.c
TEST_HARNESS := isolated
EXTRA_SRCS := ../../../../src/core/storage/storage_util.c
include ../../common.mk
