# Shared storage helpers (src/core/storage/storage_util.c): mkdir -p, rm -r,
# the capped file reader, the JSON escaper.  09-storage F-56, F-57, F-63, F-36.

TEST_NAME := storage_util
TEST_SRCS := test.c
TEST_HARNESS := isolated
EXTRA_SRCS := ../../../../src/core/storage/storage_util.c
include ../../common.mk
