#!/usr/bin/env python3
"""Embed the built gsvrom blobs as C byte arrays in one generated header.

Usage: embed.py --out gsvrom_blobs.h name=path [name=path ...]

Emits, per blob:  static const uint8_t gsvrom_<name>[] = { ... };
plus a matching gsvrom_<name>_size constant.  Deterministic output so the
generated header diffs are reviewable (proposal sec. 8).
"""

import argparse


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", required=True)
    ap.add_argument("blobs", nargs="+", metavar="name=path")
    args = ap.parse_args()

    lines = [
        "// Generated by tools/vrom/embed.py — do not edit.",
        "// GS generic NuBus declaration ROM images (see tools/vrom/).",
        "// clang-format off",
        "#ifndef GSVROM_BLOBS_H",
        "#define GSVROM_BLOBS_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
    ]
    for spec in args.blobs:
        name, path = spec.split("=", 1)
        with open(path, "rb") as f:
            data = f.read()
        lines.append(f"static const uint8_t gsvrom_{name}[{len(data)}] = {{")
        for i in range(0, len(data), 16):
            chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
            lines.append(f"    {chunk},")
        lines.append("};")
        lines.append("")
    lines.append("#endif // GSVROM_BLOBS_H")
    lines.append("// clang-format on")
    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
