# ADB keycode -> Lisa COPS keycode, checked against the boot ROM's own table.
# See test.c.

TEST_NAME    := lisa_keymap
TEST_SRCS    := test.c
TEST_HARNESS := none
STUBS        := assert
EXTRA_SRCS   := ../../../../src/machines/lisa/lisa_keymap.c
include ../../common.mk
