TEST_NAME := shell_complete
TEST_SRCS := test.c
TEST_HARNESS := isolated
EXTRA_SRCS := ../../../../src/core/job/seam.c \
              ../../../../src/core/object/value.c \
              ../../../../src/core/object/object.c \
              ../../../../src/core/object/parse.c \
              ../../../../src/core/object/meta.c \
              ../../../../src/core/object/alias.c \
              ../../../../src/core/shell/cmd_complete.c \
              ../../../../src/core/shell/commands.c \
              ../../../../src/core/shell/syntax.c
include ../../common.mk
