TEST_NAME := object_lifecycle
TEST_SRCS := test.c
TEST_HARNESS := isolated
EXTRA_SRCS := ../../../../src/core/object/value.c \
              ../../../../src/core/object/object.c \
              ../../../../src/core/object/meta.c \
              ../../../../src/core/object/json_encode.c
include ../../common.mk
