#!/usr/bin/env python3
"""Embed binary files as C byte arrays in one generated header.

Usage: bin2c.py --out header.h --guard NAME name=path [name=path ...]

Emits, per file:  static const uint8_t <name>[<size>] = { ... };
Deterministic output (input order, fixed formatting).  Generated into
build/ — never committed."""

import argparse
import os


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", required=True)
    ap.add_argument("--guard", required=True)
    ap.add_argument("blobs", nargs="+", metavar="name=path")
    args = ap.parse_args()

    lines = [
        "// Generated by scripts/bin2c.py — do not edit, do not commit.",
        f"#ifndef {args.guard}",
        f"#define {args.guard}",
        "",
        "#include <stdint.h>",
        "",
    ]
    for spec in args.blobs:
        name, path = spec.split("=", 1)
        with open(path, "rb") as f:
            data = f.read()
        lines.append(f"static const uint8_t {name}[{len(data)}] = {{")
        for i in range(0, len(data), 16):
            chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
            lines.append(f"    {chunk},")
        lines.append("};")
        lines.append("")
    lines.append(f"#endif // {args.guard}")
    # Write beside the target and rename: an interrupted or concurrent build
    # must never leave a torn header that make then considers up to date.
    tmp = f"{args.out}.{os.getpid()}.tmp"
    with open(tmp, "w") as f:
        f.write("\n".join(lines) + "\n")
    os.replace(tmp, args.out)


if __name__ == "__main__":
    main()
