#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) pappadf
#
# gen_pd_cases.py — the predecoded cores' T1 id generator.
#
# A decode tree (cpu_decode.h / ppc_decode.h) invokes one object-like OP_
# macro per leaf.  The predecoded executors need a FLAT switch over those
# leaves — one id per distinct OP_ name — which cannot be obtained by
# re-including the nested tree (a C `case` binds to the innermost enclosing
# switch).  So this script extracts the name set from the tree and emits
# three headers that agree by construction:
#
#   <prefix>_pd_t1_ids.h        enum { T1_<name> = base, ... , T1_END }
#   <prefix>_pd_t1_classify.h   #undef OP_<name> / #define OP_<name> return T1_<name>
#                               (the classifier's defaults; T0 classifiers
#                               override the names they specialize)
#   <prefix>_pd_t1_cases.h      case T1_<name>: PD_T1_BODY(OP_<name>); break;
#                               (included inside the executor's flat switch,
#                               after the core's own OP_ bindings, so each
#                               case runs whatever that core binds the name to)
#   <prefix>_pd_t1_names.h      the leaf names by id, for predecode.hist
#
# Usage: gen_pd_cases.py --tree <decode.h> --prefix <cpu|ppc> --base <id> --out <dir>

import argparse
import os
import re
import sys


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tree", required=True, help="decode tree header to scan")
    ap.add_argument("--prefix", required=True, help="output file prefix (cpu, ppc)")
    ap.add_argument("--base", required=True, type=int, help="first T1 id (after the control ids)")
    ap.add_argument("--out", required=True, help="output directory")
    args = ap.parse_args()

    with open(args.tree, "r", encoding="utf-8") as f:
        text = f.read()

    # Every OP_ token invoked in the tree (definitions never appear there);
    # sorted for a stable id assignment across builds.
    names = sorted(set(re.findall(r"\bOP_[A-Z0-9_]+\b", text)))
    if not names:
        sys.exit("gen_pd_cases: no OP_ names found in %s" % args.tree)

    os.makedirs(args.out, exist_ok=True)
    guard = args.prefix.upper()
    header = "// Generated by scripts/gen_pd_cases.py from %s — do not edit.\n" % os.path.basename(args.tree)

    ids_path = os.path.join(args.out, "%s_pd_t1_ids.h" % args.prefix)
    with open(ids_path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write("#ifndef %s_PD_T1_IDS_H\n#define %s_PD_T1_IDS_H\n" % (guard, guard))
        f.write("// One flattened-generic (T1) id per distinct OP_ leaf of the decode tree.\n")
        f.write("enum {\n")
        f.write("    T1_%s = %d,\n" % (names[0][3:], args.base))
        for n in names[1:]:
            f.write("    T1_%s,\n" % n[3:])
        f.write("    T1_END,\n")
        f.write("    T1_FIRST = %d,\n" % args.base)
        f.write("};\n")
        f.write("#define %s_PD_T1_COUNT %d\n" % (guard, len(names)))
        f.write("#endif\n")

    classify_path = os.path.join(args.out, "%s_pd_t1_classify.h" % args.prefix)
    with open(classify_path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write("// Classifier defaults: every leaf returns its T1 id.  Included with the\n")
        f.write("// OP_ names undefined; T0 classifiers redefine the shapes they specialize.\n")
        for n in names:
            f.write("#undef %s\n#define %s return T1_%s\n" % (n, n, n[3:]))

    names_path = os.path.join(args.out, "%s_pd_t1_names.h" % args.prefix)
    with open(names_path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write("// Leaf names by T1 id (index = id - base), for the decode histogram.\n")
        f.write("static const char *const %s_pd_t1_names[%d] = {\n" % (args.prefix, len(names)))
        for n in names:
            f.write('    "%s",\n' % n[3:])
        f.write("};\n")

    cases_path = os.path.join(args.out, "%s_pd_t1_cases.h" % args.prefix)
    with open(cases_path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write("// The flat T1 switch body: one case per leaf, running the core's OP_ body.\n")
        f.write("// PD_T1_BODY(x) is the includer's per-case prologue + body wrapper.\n")
        for n in names:
            f.write("case T1_%s: PD_T1_BODY(%s); break;\n" % (n[3:], n))

    print("gen_pd_cases: %d %s leaves -> %s" % (len(names), args.prefix, args.out))


if __name__ == "__main__":
    main()
