#!/usr/bin/env bash
# Idempotent installer for a pinned Emscripten toolchain (4.0.10 by default).
# Usage: scripts/setup_emsdk.sh [version]
set -euo pipefail

REQ_VERSION="${1:-4.0.10}"
INSTALL_DIR="${EMSDK_ROOT:-$PWD/.emsdk}" # local clone to avoid polluting system

if command -v emcc >/dev/null 2>&1; then
  CURR=$(emcc --version 2>/dev/null | head -n1 | sed -E 's/.*emcc \(Emscripten gcc/clang-like replacement\) ([0-9.]+).*/\1/' || true)
  if [[ "$CURR" == "$REQ_VERSION" ]]; then
    echo "Emscripten $CURR already present on PATH" >&2
    exit 0
  else
    echo "Found emcc version $CURR but $REQ_VERSION requested; continuing with local install" >&2
  fi
fi

if [[ -x "$INSTALL_DIR/emsdk" ]]; then
  echo "Updating existing emsdk in $INSTALL_DIR" >&2
  git -C "$INSTALL_DIR" fetch --depth 1 origin || true
else
  echo "Cloning emsdk into $INSTALL_DIR" >&2
  git clone --depth 1 https://github.com/emscripten-core/emsdk.git "$INSTALL_DIR"
fi

pushd "$INSTALL_DIR" >/dev/null
./emsdk install "$REQ_VERSION"
./emsdk activate "$REQ_VERSION"
source ./emsdk_env.sh >/dev/null 2>&1 || true
popd >/dev/null

cat > .emsdk_env <<EOF
# Generated by setup_emsdk.sh
export EMSDK="$INSTALL_DIR"
export EM_CONFIG="$INSTALL_DIR/.emscripten"
export EM_CACHE="$INSTALL_DIR/upstream/emscripten/cache"
export PATH="$INSTALL_DIR:$INSTALL_DIR/upstream/emscripten:$INSTALL_DIR/node/$(ls "$INSTALL_DIR"/node | head -n1)/bin:$PATH"
EOF

echo "Pinned Emscripten $REQ_VERSION installed. Source .emsdk_env to use in current shell:"
echo "  source .emsdk_env"