TEST_NAME := object_api
TEST_SRCS := test.c
TEST_HARNESS := isolated
EXTRA_SRCS := ../../../../src/core/object/api.c \
              ../../../../src/core/object/value.c \
              ../../../../src/core/object/object.c \
              ../../../../src/core/object/meta.c \
              ../../../../src/core/object/parse.c \
              ../../../../src/core/object/value_format.c
include ../../common.mk
