<script lang="ts">
  import Modal from '@/components/common/Modal.svelte';
  import Button from '@/components/ui/Button.svelte';
  import Field from '@/components/ui/Field.svelte';
  import TextInput from '@/components/ui/TextInput.svelte';

  // Asks for one line of text: a name, a label, a file name.  `validate`
  // answers an error to show under the field (the dialog stays open) or ''.
  // An empty answer closes it like Cancel.
  interface Props {
    open: boolean;
    title: string;
    label: string;
    initial: string;
    submitText?: string;
    validate?: (value: string) => string;
    /** The field's id (a stable hook for tests); generated by default. */
    inputId?: string;
    onSubmit: (value: string) => void;
    onClose: () => void;
  }
  let {
    open,
    title,
    label,
    initial,
    submitText = 'OK',
    validate = () => '',
    inputId: givenId,
    onSubmit,
    onClose,
  }: Props = $props();
  const autoId = $props.id();
  const inputId = $derived(givenId ?? autoId);

  // Captures the initial value once; the $effect below re-syncs whenever
  // the dialog re-opens with a new target.
  // svelte-ignore state_referenced_locally
  let value = $state(initial);
  let inputEl = $state<HTMLInputElement | null>(null);
  let error = $state('');

  $effect(() => {
    if (open) {
      value = initial;
      error = '';
      // Focus + select after mount.
      requestAnimationFrame(() => {
        inputEl?.focus();
        inputEl?.select();
      });
    }
  });

  function commit() {
    const v = value.trim();
    if (!v) {
      onClose();
      return;
    }
    const why = validate(v);
    if (why) {
      error = why;
      return;
    }
    onSubmit(v);
  }

  function onKey(ev: KeyboardEvent) {
    if (ev.key === 'Enter') {
      ev.preventDefault();
      commit();
    } else if (ev.key === 'Escape') {
      ev.preventDefault();
      onClose();
    }
  }
</script>

<Modal {open} {title} {onClose}>
  <div class="rename-body">
    <Field stacked {label} for={inputId} {error}>
      <TextInput
        id={inputId}
        class="rename-input"
        size="lg"
        bind:value
        bind:ref={inputEl}
        invalid={!!error}
        onkeydown={onKey}
        oninput={() => (error = '')}
      />
    </Field>
  </div>
  {#snippet actions()}
    <Button size="lg" class="btn" onclick={onClose}>Cancel</Button>
    <Button size="lg" variant="primary" class="btn primary" onclick={commit}>{submitText}</Button>
  {/snippet}
</Modal>

<style>
  .rename-body {
    min-width: 280px;
  }
</style>
