TEST_NAME := ndif
TEST_SRCS := test.c
TEST_HARNESS := isolated
EXTRA_SRCS := ../../../../src/core/storage/adc.c \
              ../../../../src/core/storage/image_ndif.c \
              ../../../../src/core/storage/resource_fork.c \
              ../../../../src/core/storage/macroman.c \
              ../../../../src/core/storage/rsrc_dcmp.c
include ../../common.mk
