// SPDX-License-Identifier: MIT
// Copyright (c) pappadf

// builtin_se30_video.c
// SE/30 built-in video as a NuBus card living in slot $E.  Implements the
// nubus_card_ops_t vtable plus the SE/30-specific hooks declared in
// builtin_se30_video.h.  See proposal-machine-iicx-iix.md §3.2.5.
//
// What the card owns:
//   * 64 KB VRAM at $FEE00000
//   * 32 KB declaration ROM at $FEFF8000 (the real SE/30 onboard-video vROM
//     when one was offered — found by content via declrom_load_vrom_card —
//     synthesised fallback otherwise; the byte-banged synth is the same
//     220-line sequence se30.c used to carry inline)
//   * the display_t exposed via system_display() — 512×342×1bpp, with
//     `bits` toggled between primary and alternate VRAM offsets when
//     se30_via1_output reports a VIA1 PA6 change

#include "builtin_se30_video.h"
#include "card.h"
#include "checkpoint.h"
#include "declrom.h"
#include "display.h"
#include "gsvrom.h"
#include "log.h"
#include "system.h"
#include "system_config.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

LOG_USE_CATEGORY_NAME("se30video");

#define SE30_VRAM_SIZE           0x00010000UL // 64 KB
#define SE30_VROM_SIZE           0x00008000UL // 32 KB
#define SE30_FB_PRIMARY_OFFSET   0x8040
#define SE30_FB_ALTERNATE_OFFSET 0x0040

// Per-card private state.  Hangs off card->priv.
typedef struct {
    uint8_t *vram;
    uint8_t *vrom;
    char *vrom_path; // path the VROM was loaded from; NULL if synthesised
    bool main_buf; // true: primary, false: alternate
    display_t display;
} se30_priv_t;

// === VROM loading / synth (moved verbatim from se30.c) ======================

// Build a minimal fallback NuBus declaration ROM when no real
// onboard-video vROM was offered.  The records are generated by the
// declrom builder (runtime-vrom proposal stage B — this replaces the
// 220-line byte-banged image inherited from se30.c); the two 68K code
// blocks are spliced verbatim and carry the same bytes the byte-banged
// image did.

// PrimaryInit sExecBlock: 12-byte sExec header (size, rev $02, CPU 2 =
// 68020, code offset +4) followed by the code.  Self-contained: the
// trailing $0E80 word is the PRAM data the LEA data(PC) reads.
static const uint8_t se30_fallback_primaryinit[] = {
    0x00, 0x00, 0x00, 0x6A, // block size (incl. self) = 106
    0x02, 0x02, 0x00, 0x00, // revision 2, CPU 68020, reserved
    0x00, 0x00, 0x00, 0x04, // self-relative code offset
    0x31, 0x7C, 0x00, 0x01, 0x00, 0x02, // MOVE.W #1,spResult(A0)
    0x41, 0xFA, 0x00, 0x6A, // LEA data(PC),A0
    0x20, 0x3C, 0x00, 0x02, 0x00, 0x80, // MOVE.L #$00020080,D0
    0xA0, 0x52, // _WriteXPRam
    0x20, 0x78, 0x01, 0xD4, // MOVEA.L $01D4.W,A0 (VIA1 base)
    0x08, 0xE8, 0x00, 0x06, 0x06, 0x00, // BSET #6,$600(A0)
    0x08, 0xE8, 0x00, 0x06, 0x04, 0x00, // BSET #6,$400(A0)
    0x08, 0xE8, 0x00, 0x06, 0x1E, 0x00, // BSET #6,$1E00(A0)
    0x08, 0xD0, 0x00, 0x06, // BSET #6,(A0)
    0x22, 0x7C, 0xFE, 0xE0, 0x00, 0x00, // MOVEA.L #$FEE00000,A1
    0x24, 0x49, // MOVEA.L A1,A2
    0x2A, 0x3C, 0xAA, 0xAA, 0xAA, 0xAA, // MOVE.L #$AAAAAAAA,D5
    0xD3, 0xFC, 0x00, 0x00, 0x80, 0x40, // ADDA.L #$8040,A1
    0x36, 0x3C, 0x01, 0x55, // MOVE.W #$155,D3
    0x34, 0x3C, 0x00, 0x0F, // MOVE.W #$F,D2
    0x22, 0xC5, 0x51, 0xCA, 0xFF, 0xFC, 0x46, 0x85, 0x51, 0xCB, 0xFF, 0xF2, 0x22, 0x4A, 0xD2,
    0xFC, 0x00, 0x40, 0x36, 0x3C, 0x01, 0x55, 0x34, 0x3C, 0x00, 0x0F, 0x22, 0xC5, 0x51, 0xCA,
    0xFF, 0xFC, 0x46, 0x85, 0x51, 0xCB, 0xFF, 0xF2, 0x70, 0x00, 0x4E, 0x75, 0x0E, 0x80,
};

// Stub DRVR sBlock: DRVR header + name ".Display_Video_Apple_SE30" +
// no-op Open/Control/Status routines (MOVEQ #0,D0; RTS).
static const uint8_t se30_fallback_drvr[] = {
    0x00, 0x00, 0x00, 0x38, 0x4F, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x2C, 0x00,
    0x00, 0x00, 0x30, 0x00, 0x34, 0x00, 0x2C, 0x19, 0x2E, 0x44, 0x69, 0x73, 0x70, 0x6C, 0x61,
    0x79, 0x5F, 0x56, 0x69, 0x64, 0x65, 0x6F, 0x5F, 0x41, 0x70, 0x70, 0x6C, 0x65, 0x5F, 0x53,
    0x45, 0x33, 0x30, 0x70, 0x00, 0x4E, 0x75, 0x70, 0x00, 0x4E, 0x75, 0x70, 0x00, 0x4E, 0x75,
};

static void synthesise_vrom_fallback(uint8_t *rom) {
    memset(rom, 0, SE30_VROM_SIZE);
    declrom_builder_t *b = declrom_builder_new(0x2000);
    if (!b)
        return;
    // Same identity and records the byte-banged image declared: BoardId
    // $0C, one 512×342×1 video sResource ($80) with two pages (primary +
    // alternate buffer), framebuffer at device base + $8040.
    static const declrom_vidmode_t mode = {
        .base_offset = SE30_FB_PRIMARY_OFFSET,
        .row_bytes = 64,
        .width = 512,
        .height = 342,
        .pixel_type = 0, // chunky indexed
        .pixel_size = 1,
        .cmp_count = 1,
        .cmp_size = 1,
        .dev_type = 0, // settable CLUT
        .page_count = 2,
    };
    static const declrom_vidsrsrc_t vid = {
        .name = "Built-in Video",
        .drhw = 0x0009, // SE/30 built-in video DrHW
        .flags = 0, // absent, like the byte-banged image
        .use_major = false,
        .base = 0,
        .length = SE30_FB_PRIMARY_OFFSET + 64 * 342,
        .modes = &mode,
        .mode_count = 1,
    };
    bool ok = declrom_set_board(b, "Macintosh SE/30", 0x000C) &&
              declrom_add_exec(b, DECLROM_PRIMARY_INIT, se30_fallback_primaryinit, sizeof(se30_fallback_primaryinit)) &&
              declrom_add_drvr(b, se30_fallback_drvr, sizeof(se30_fallback_drvr)) &&
              declrom_add_video_srsrc(b, 0x80, &vid) && declrom_finalise(b, 0x0F);
    if (ok) {
        // Tail-place the dense $0F image at the top of the 32 KB window,
        // exactly like a loaded chip (Format Block ends at the slot top).
        size_t n = 0;
        const uint8_t *img = declrom_builder_bytes(b, &n);
        if (!declrom_layout_chip(img, n, rom, SE30_VROM_SIZE, 0x0F))
            ok = false;
    }
    if (!ok)
        LOG(0, "se30: fallback declaration-ROM generation failed; slot will read as empty");
    declrom_builder_free(b);
}

// Load the real onboard-video declaration ROM through the shared content-
// driven loader (the offer registry the platform populated — no search, no
// filenames).  The SE/30's chip is byteLanes $0F (4-lane, flat copy), so it
// fills the whole 32 KB window.  Stores the path used in *out_path (caller
// takes ownership) on success.
static bool load_real_vrom(uint8_t *vrom_buf, char **out_path) {
    *out_path = NULL;
    if (!declrom_load_vrom_card(builtin_se30_video_kind.id, vrom_buf, SE30_VROM_SIZE, out_path)) {
        LOG(0, "No SE/30 onboard-video vROM offered — falling back to the synthesised declaration ROM");
        return false;
    }
    LOG(1, "Loaded real VROM from %s", *out_path);
    return true;
}

// === Card vtable ============================================================

static int card_init_common(nubus_card_t *card, config_t *cfg, checkpoint_t *cp, bool generic) {
    (void)cp;
    se30_priv_t *p = calloc(1, sizeof(*p));
    if (!p)
        return -1;
    p->vram = calloc(1, SE30_VRAM_SIZE);
    p->vrom = calloc(1, SE30_VROM_SIZE);
    if (!p->vram || !p->vrom) {
        free(p->vram);
        free(p->vrom);
        free(p);
        return -1;
    }
    (void)cfg;
    if (generic) {
        // Generic sibling kind ("se30"): generate the GS declaration ROM —
        // a full declaration ROM with a real display driver, records from
        // builtin_se30_monitors[], code fragments spliced, CRC stamped in C
        // (proposal-nubus-runtime-vrom §4).  The offer registry is never
        // consulted.
        declrom_builder_t *bld = gsvrom_generate(GSVROM_SE30, builtin_se30_video_generic_kind.monitors);
        size_t img_size = 0;
        const uint8_t *img = bld ? declrom_builder_bytes(bld, &img_size) : NULL;
        if (!img ||
            !declrom_install_builtin(builtin_se30_video_generic_kind.id, img, img_size, p->vrom, SE30_VROM_SIZE))
            LOG(0, "se30: built-in declaration ROM failed to generate; declaration ROM is zero-filled");
        declrom_builder_free(bld);
    } else if (!load_real_vrom(p->vrom, &p->vrom_path)) {
        if (!cp) {
            // Real VROM was the long-standing requirement on cold boot;
            // fall back to the synthesised image so the real kind keeps
            // booting even when no onboard-video vROM was offered.
            synthesise_vrom_fallback(p->vrom);
        }
        // Restoring from a checkpoint?  The VROM contents will be overwritten
        // from the checkpoint stream; an empty buffer here is fine.
    }

    // Populate the display descriptor.  Primary buffer at $8040 is the
    // boot-time selection — VIA1 PA6 will toggle it before the OS draws.
    p->main_buf = true;
    p->display.width = 512;
    p->display.height = 342;
    p->display.stride = 512 / 8;
    p->display.format = PIXEL_1BPP_MSB;
    p->display.bits = p->vram + SE30_FB_PRIMARY_OFFSET;
    p->display.clut = NULL;
    p->display.clut_len = 0;
    p->display.shape_dirty = true;
    p->display.fb_dirty = true;

    card->priv = p;
    return 0;
}

static void card_teardown(nubus_card_t *card, config_t *cfg) {
    (void)cfg;
    se30_priv_t *p = card->priv;
    if (!p)
        return;
    free(p->vram);
    free(p->vrom);
    free(p->vrom_path);
    free(p);
    card->priv = NULL;
}

static display_t *card_display(nubus_card_t *card) {
    se30_priv_t *p = card->priv;
    return p ? &p->display : NULL;
}

static const char *card_name(const nubus_card_t *card) {
    (void)card;
    return "Macintosh SE/30 Built-in Video";
}

// Thin per-kind init wrappers — the sibling pair shares one HLE model
// (proposal-generic-nubus-vrom sec. 6.1: "one HLE model per pair").
static int card_init_real(nubus_card_t *card, config_t *cfg, checkpoint_t *cp) {
    return card_init_common(card, cfg, cp, /*generic*/ false);
}

static int card_init_generic(nubus_card_t *card, config_t *cfg, checkpoint_t *cp) {
    return card_init_common(card, cfg, cp, /*generic*/ true);
}

static const char *card_name_generic(const nubus_card_t *card) {
    (void)card;
    return "Macintosh SE/30 Built-in Video (generic video ROM)";
}

static const nubus_card_ops_t builtin_se30_video_ops = {
    .init = card_init_real,
    .teardown = card_teardown,
    .on_vbl = NULL, // VBL slot-IRQ flow stays in se30_trigger_vbl for v1
    .display = card_display,
    .name = card_name,
};

static const nubus_card_ops_t builtin_se30_video_generic_ops = {
    .init = card_init_generic,
    .teardown = card_teardown,
    .on_vbl = NULL,
    .display = card_display,
    .name = card_name_generic,
};

// === Factory + kind descriptor ==============================================

static nubus_card_t *factory_common(int slot, config_t *cfg, checkpoint_t *cp, const nubus_card_ops_t *ops) {
    nubus_card_t *card = calloc(1, sizeof(*card));
    if (!card)
        return NULL;
    card->ops = ops;
    card->slot = slot;
    if (card->ops->init(card, cfg, cp) != 0) {
        free(card);
        return NULL;
    }
    return card;
}

static nubus_card_t *factory(int slot, config_t *cfg, checkpoint_t *cp) {
    return factory_common(slot, cfg, cp, &builtin_se30_video_ops);
}

static nubus_card_t *factory_generic(int slot, config_t *cfg, checkpoint_t *cp) {
    return factory_common(slot, cfg, cp, &builtin_se30_video_generic_ops);
}

// One monitor entry — the SE/30 built-in is fixed at 512×342×1bpp; the
// list is included so the dialog's monitor dropdown has *something* to
// show even though the user can't change it.
static const int builtin_se30_depths[] = {1, 0};
static const nubus_monitor_t builtin_se30_monitors[] = {
    {.id = "se30_internal",
     .name = "Built-in 9\" CRT",
     .width = 512,
     .height = 342,
     .depths = builtin_se30_depths,
     // The generated GS vROM's functional sResource id (gsvrom_generate
     // uses srsrc_sister as the spID; the assembled images used $80).
     .srsrc_sister = 0x80},
    {0},
};

const nubus_card_kind_t builtin_se30_video_kind = {
    .id = "builtin_se30_video",
    .display_name = "Macintosh SE/30 Built-in Video",
    .attach = CARD_ATTACH_BUILTIN, // motherboard circuitry — never socketed
    // The SE/30 carries no video declaration ROM in main ROM; it needs a
    // separate onboard-video vROM file (the dialog's VROM picker drives this).
    .requires_vrom = true,
    .monitors = builtin_se30_monitors,
    .factory = factory,
};

// Generic sibling kind ("se30") with the built-in GS declaration ROM —
// the SE/30 profile's default, so every SE/30 boots with working video
// and no uploaded vROM (proposal-generic-nubus-vrom sec. 7.4).  The
// real kind stays selectable via video_card= when a dump is offered.
const nubus_card_kind_t builtin_se30_video_generic_kind = {
    .id = "se30",
    .display_name = "Macintosh SE/30 Built-in Video (generic video ROM)",
    .attach = CARD_ATTACH_BUILTIN,
    .requires_vrom = false,
    .monitors = builtin_se30_monitors,
    .factory = factory_generic,
};

// === SE/30-specific public hooks ============================================

void builtin_se30_video_select_buffer(nubus_card_t *card, bool main_buf) {
    if (!card)
        return;
    se30_priv_t *p = card->priv;
    if (!p || p->main_buf == main_buf)
        return;
    p->main_buf = main_buf;
    p->display.bits = p->vram + (main_buf ? SE30_FB_PRIMARY_OFFSET : SE30_FB_ALTERNATE_OFFSET);
    p->display.fb_dirty = true;
}

uint8_t *builtin_se30_video_vram(nubus_card_t *card) {
    se30_priv_t *p = card ? card->priv : NULL;
    return p ? p->vram : NULL;
}

uint8_t *builtin_se30_video_vrom(nubus_card_t *card) {
    se30_priv_t *p = card ? card->priv : NULL;
    return p ? p->vrom : NULL;
}

const char *builtin_se30_video_vrom_path(nubus_card_t *card) {
    se30_priv_t *p = card ? card->priv : NULL;
    return p ? p->vrom_path : NULL;
}

void builtin_se30_video_checkpoint_save_vram(nubus_card_t *card, checkpoint_t *cp) {
    se30_priv_t *p = card ? card->priv : NULL;
    if (!p)
        return;
    system_write_checkpoint_data(cp, p->vram, SE30_VRAM_SIZE);
}

void builtin_se30_video_checkpoint_restore_vram(nubus_card_t *card, checkpoint_t *cp) {
    se30_priv_t *p = card ? card->priv : NULL;
    if (!p)
        return;
    system_read_checkpoint_data(cp, p->vram, SE30_VRAM_SIZE);
    // Re-derive display.bits in case the checkpoint stream restores
    // VIA1 PA6 to a value that toggles the buffer (via_redrive_outputs
    // will fire after we return).
    p->display.bits = p->vram + (p->main_buf ? SE30_FB_PRIMARY_OFFSET : SE30_FB_ALTERNATE_OFFSET);
    p->display.fb_dirty = true;
}
