TEST_NAME := resfork
TEST_SRCS := test.c
TEST_HARNESS := isolated
EXTRA_SRCS := ../../../../src/core/storage/resource_fork.c \
              ../../../../src/core/storage/macroman.c \
              ../../../../src/core/storage/rsrc_dcmp.c \
              ../../../../src/core/storage/storage_util.c
include ../../common.mk
