TEST_NAME := udif
TEST_SRCS := test.c
TEST_HARNESS := isolated
EXTRA_SRCS := ../../../../src/core/storage/adc.c \
              ../../../../src/core/storage/image_udif.c \
              ../../../../src/core/storage/inflate.c
include ../../common.mk
