# The microphone ring's consumer arithmetic (src/platform/wasm/em_mic_ring.c)
# at the wrap of its free-running indices.  See test.c.

TEST_NAME    := mic_ring
TEST_SRCS    := test.c
TEST_HARNESS := none
STUBS        := assert
EXTRA_SRCS   := ../../../../src/platform/wasm/em_mic_ring.c
include ../../common.mk
